name: Linky
description: Sync Energy dashboards with your Linky smart meter
version: 1.2.0
slug: linky
init: false
url: https://github.com/drappier-charles/ha-linky-tempo
image: sindar/ha-linky
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
homeassistant_api: true
options:
  client id tempo: ''
  client secret tempo: ''
  consumption PRM: ''
  consumption token: ''
  consumption name: 'Linky consumption'
  consumption action: sync

schema:
  client id tempo: str?
  client secret tempo: str?
  consumption PRM: str?
  consumption token: str?
  consumption name: str
  consumption action: list(sync|reset)
