name: LinkyTempo
description: Sync Energy dashboards with your Linky smart meter with Tempo pricing
version: 1.0.27
slug: linkytempo
init: false
url: https://github.com/drappier-charles/ha-linky-tempo
image: sindar/ha-linky
startup: services
panel_title: Energie Tempo
panel_icon: mdi:lightning-bolt
arch:
  - aarch64
homeassistant_api: true
ingress: true
ingress_port: 1337
ingress_stream: true
ports:
  1337/tcp: 1337
ports_description:
  1337/tcp: Linky Tempo Interface
options:
  LINKY_PRM: ''
  LINKY_TOKEN: ''
  TEMPO_CLIENT_ID: ''
  TEMPO_CLIENT_SECRET: ''
  INTERVAL: 7
  TEMPO_PRICE_STANDARD: 0.2516
  TEMPO_PRICE_STANDARD_HC: 0.2068
  TEMPO_PRICE_STANDARD_HP: 0.27
  TEMPO_PRICE_BLUE_HC: 0.1296
  TEMPO_PRICE_BLUE_HP: 0.1609
  TEMPO_PRICE_WHITE_HC:  0.1486
  TEMPO_PRICE_WHITE_HP: 0.1894
  TEMPO_PRICE_RED_HC:  0.1568
  TEMPO_PRICE_RED_HP: 0.7562
  EDF_MONTHLY_SUBSCRIPTION: 16.16
  PURGE: 'false'
  CRON_CONFIG: 33 34 6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23 * * *
schema:
  LINKY_PRM: str?
  LINKY_TOKEN: str?
  TEMPO_CLIENT_ID: str?
  TEMPO_CLIENT_SECRET: str?
  INTERVAL: int?
  TEMPO_PRICE_STANDARD: float?
  TEMPO_PRICE_STANDARD_HC: float?
  TEMPO_PRICE_STANDARD_HP: float?
  TEMPO_PRICE_BLUE_HC: float?
  TEMPO_PRICE_BLUE_HP: float?
  TEMPO_PRICE_WHITE_HC: float?
  TEMPO_PRICE_WHITE_HP: float?
  TEMPO_PRICE_RED_HC: float?
  TEMPO_PRICE_RED_HP: float?
  EDF_MONTHLY_SUBSCRIPTION: float?
  PURGE: str?
  CRON_CONFIG: str?