name: LinkyTempo
description: Sync Energy dashboards with your Linky smart meter with Tempo pricing
version: 1.0.2
slug: linkytempo
init: false
url: https://github.com/drappier-charles/ha-linky-tempo
image: sindar/ha-linky
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
homeassistant_api: true
options:
  LINKY_PRM: ''
  LINKY_TOKEN: ''
  TEMPO_CLIENT_ID: ''
  TEMPO_CLIENT_SECRET: ''
  INTERVAL: 14
  TEMPO_PRICE_BLUE_HC: 0.1296
  TEMPO_PRICE_BLUE_HP: 0.1609
  TEMPO_PRICE_WHITE_HC:  0.1486
  TEMPO_PRICE_WHITE_HP: 0.1894
  TEMPO_PRICE_RED_HC:  0.1568
  TEMPO_PRICE_RED_HP: 0.7562
  EDF_MONTHLY_SUBSCRIPTION: 16.16
  PURGE: 'false'
schema:
  LINKY_PRM: str?
  LINKY_TOKEN: str?
  TEMPO_CLIENT_ID: str?
  TEMPO_CLIENT_SECRET: str?
  INTERVAL: int?
  TEMPO_PRICE_BLUE_HC: float?
  TEMPO_PRICE_BLUE_HP: float?
  TEMPO_PRICE_WHITE_HC: float?
  TEMPO_PRICE_WHITE_HP: float?
  TEMPO_PRICE_RED_HC: float?
  TEMPO_PRICE_RED_HP: float?
  EDF_MONTHLY_SUBSCRIPTION: float?
  PURGE: str?